name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify a Python version, e.g., 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Installation
        run: |
          python --version
          pip --version
          pip list

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure Python is set up for this job as well

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest --maxfail=5 --disable-warnings

      - name: Security Checks
        run: |
          pip install bandit pip-audit
          bandit -r .
          pip-audit

  packaging:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Package
        run: |
          python setup.py sdist
