name: CI/CD Pipeline for nexScan

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t nexscan:latest .

    # Log in to DockerHub (if you're pushing to DockerHub, modify as per your registry)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Docker image to DockerHub (or your registry)
    - name: Push Docker image
      run: |
        docker tag nexscan:latest ${{ secrets.DOCKER_USERNAME }}/nexscan:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nexscan:latest

    # Set up SSH for deployment
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Deploy the Docker container to your server
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no username@your-server-ip "docker pull ${{ secrets.DOCKER_USERNAME }}/nexscan:latest && docker run -d --restart unless-stopped --name nexscan-container ${{ secrets.DOCKER_USERNAME }}/nexscan:latest"
