name: Deploy Docker Image to Remote Server

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/nexscan:latest .
        docker push your-dockerhub-username/nexscan:latest

    - name: Deploy to remote server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} username@your-server-ip \
        "docker pull your-dockerhub-username/nexscan:latest && docker run -d --restart unless-stopped --name nexscan-container your-dockerhub-username/nexscan:latest"
