name: CI/CD Pipeline for nexScan

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checkout your code

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: vdh05  # Docker Hub username stored in secrets
        password: Vidhi$3800   # Docker Hub password stored in secrets

    - name: Build Docker image
      run: |
        docker build -t vdh05/nexscan:latest .  # Build your Docker image

    - name: Push Docker image to Docker Hub
      run: |
        docker push vdh05/nexscan:latest  # Push the image to Docker Hub

  deploy:
    runs-on: ubuntu-latest  # Run deployment job on the latest Ubuntu environment
    needs: build  # Make sure the build job completes before deploying

    steps:
    - name: Trigger Webhook on Server (Alternative to SSH)
      run: |
        curl -X POST http://192.168.1.100/webhook  # Trigger the deployment script on your server
